// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "auth": {
    "login": {
      "description": "Enter your email below to login to your account",
      "forgot_password": "Forgot your password?",
      "login_with_github": "Login with GitHub",
      "no_account": "Don't have an account?",
      "password": "Password",
      "password_placeholder": "Enter your password",
      "sign_up": "Sign up",
      "title": "Login to your account",
      "username_or_email": "Username or Email",
      "username_or_email_placeholder": "Enter your username or email"
    },
    "register": {
      "confirm_password": "Confirm Password",
      "confirm_password_placeholder": "Confirm your password",
      "description": "Enter your details below to create your account",
      "email": "Email",
      "email_placeholder": "Enter your email",
      "has_account": "Already have an account?",
      "log_in": "Log in",
      "password": "Password",
      "password_placeholder": "Enter your password",
      "register_with_github": "Register with GitHub",
      "title": "Create an account",
      "username": "Username",
      "username_placeholder": "Enter your username"
    }
  },
  "common": {
    "actions": {
      "actions": "Actions",
      "open_menu": "Open menu",
      "refresh_schemas": "Refresh Schemas",
      "select_all": "Select all",
      "select_row": "Select row",
      "view_content": "View Content"
    },
    "buttons": {
      "back": "Back",
      "back_to_dashboard": "Back to dashboard",
      "cancel": "Cancel",
      "create": "Create",
      "delete": "Delete",
      "deleting": "Deleting...",
      "edit": "Edit",
      "go_back": "Go Back",
      "loading": "Loading...",
      "logging_in": "Logging in...",
      "login": "Login",
      "next": "Next",
      "previous": "Previous",
      "register": "Register",
      "save": "Save",
      "save_changes": "Save Changes",
      "saving": "Saving...",
      "submit": "Submit"
    },
    "confirmations": {
      "are_you_sure": "Are you sure?",
      "cannot_be_undone": "This action cannot be undone.",
      "delete_item": "This will permanently delete this item.",
      "delete_items": "This will permanently delete {{count}} selected items.",
      "delete_menu": "This will permanently delete the menu and all its content."
    },
    "empty_states": {
      "empty": "Empty",
      "no_content_found": "No content found",
      "no_results": "No results.",
      "not_found": "Not Found",
      "unknown": "Unknown"
    },
    "labels": {
      "is_free": "Free",
      "menu_name": "Menu Name",
      "select_theme": "Select a theme",
      "theme_selected": "Theme Selected: {{id}}"
    },
    "messages": {
      "content_schema_description": "Content schema for this menu item",
      "items": "{{count}} items",
      "no_properties_defined": "No properties defined",
      "or_continue_with": "Or continue with",
      "properties": "{{count}} properties",
      "properties_defined": "{{count}} properties defined"
    }
  },
  "content": {
    "add_new_content": "Add New Content",
    "content_updated": "Content updated successfully",
    "create_new_content": "Create a new content",
    "failed_to_delete": "Failed to delete item(s)",
    "failed_to_load": "Failed to load content item",
    "failed_to_update": "Failed to update content",
    "item_deleted": "Item deleted successfully",
    "items_deleted": "Successfully deleted {{count}} items",
    "loading_content": "Loading content...",
    "new_content_dialog": {
      "add_new_content": "Add New Content",
      "success": "Content created successfully",
      "title": "New Content"
    },
    "no_content_description": "This menu doesn't have any content available."
  },
  "error": {
    "404": "404",
    "404_description": "The requested page could not be found.",
    "error": "Error",
    "error_getting_menu": "Error getting menu",
    "error_getting_menus": "Error getting menus",
    "error_getting_themes": "Error getting themes",
    "error_loading_user_data": "Error loading user data",
    "error_updating_menu": "Error updating menu",
    "failed_to_create_menu": "Failed to create menu",
    "failed_to_delete_menu": "Failed to delete menu",
    "failed_to_load_content_data": "Failed to load content data",
    "failed_to_load_menu_data": "Failed to load menu data",
    "login_failed": "Login failed",
    "requested_content_not_found": "The requested content could not be found.",
    "unexpected_error": "An unexpected error occurred.",
    "upload_failed": "Upload failed"
  },
  "home": {
    "logged_in_success": "You are successfully logged in!",
    "manage_menus": "Manage Menus",
    "settings": "Settings",
    "title": "Dashboard Home"
  },
  "menu": {
    "build": "Build",
    "change_theme": "Change Theme",
    "content_title": "{{contentName}} Content",
    "create_first_menu": "Create your first menu",
    "delete_selected": "Delete Selected ({{count}})",
    "edit_content": "Edit Content",
    "edit_content_description": "Update the content for {{contentName}} in {{menuName}}",
    "edit_content_title": "Edit {{contentName}} Content",
    "menu_content": "Menu Content",
    "menu_deleted_success": "Successfully deleted menu",
    "new_menu": "+ New Menu",
    "no_menus": "No menus found.",
    "no_schemas": "No schemas found",
    "no_schemas_description": "This menu doesn't have any content schemas available.",
    "title": "Your Menus"
  },
  "settings": {
    "active_sessions": "Active Sessions"
  },
  "sidebar": {
    "app_name": "QR Menu",
    "home": "Home",
    "logout": "Logout",
    "menu": "Menu",
    "settings": "Settings",
    "themes": "Themes"
  },
  "theme": {
    "all_themes": "All Themes",
    "new_theme": "+ New Theme",
    "no_themes": "No themes found.",
    "register": {
      "preview_image": "Theme Preview Image (optional)",
      "success": "Theme registered successfully",
      "theme_zip_file": "Theme ZIP File",
      "title": "Theme Register"
    },
    "title": "Themes"
  },
  "validation": {
    "confirm_password_min": "Confirm Password must be at least 8 characters",
    "file_upload_image": "Please upload an image file, and less than 5MB",
    "file_upload_zip": "Please upload a zip file, and less than 5MB",
    "invalid_email": "Invalid email address",
    "name_required": "Name is required",
    "password_min": "Password must be at least 8 characters",
    "passwords_dont_match": "Passwords don't match",
    "theme_required": "Theme is required",
    "username_min": "Username must be at least 3 characters",
    "username_or_email_invalid": "Must be a valid username or email",
    "username_or_email_min": "Username or email must be at least 3 characters"
  }
}

export default Resources;
