// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
	auth: {
		forgot_password: {
			back_to_login: "Back to Login";
			description: "Enter your email address and we'll send you a link to reset your password";
			email: "Email";
			email_placeholder: "Enter your email";
			submit: "Send Reset Link";
			success_message: "If an account with that email exists, we've sent a password reset link to your email.";
			title: "Forgot Password";
		};
		login: {
			description: "Enter your email below to login to your account";
			forgot_password: "Forgot your password?";
			login_with_github: "Login with GitHub";
			no_account: "Don't have an account?";
			password: "Password";
			password_placeholder: "Enter your password";
			sign_up: "Sign up";
			title: "Login to your account";
			username_or_email: "Username or Email";
			username_or_email_placeholder: "Enter your username or email";
		};
		register: {
			confirm_password: "Confirm Password";
			confirm_password_placeholder: "Confirm your password";
			description: "Enter your details below to create your account";
			email: "Email";
			email_placeholder: "Enter your email";
			has_account: "Already have an account?";
			log_in: "Log in";
			password: "Password";
			password_placeholder: "Enter your password";
			register_with_github: "Register with GitHub";
			title: "Create an account";
			username: "Username";
			username_placeholder: "Enter your username";
		};
		reset_password: {
			back_to_login: "Back to Login";
			confirm_password: "Confirm Password";
			confirm_password_placeholder: "Confirm your new password";
			description: "Enter your new password below";
			invalid_token: "Invalid or expired reset token. Please request a new password reset link.";
			new_password: "New Password";
			new_password_placeholder: "Enter your new password";
			request_new_link: "Request New Reset Link";
			submit: "Reset Password";
			success_message: "Password reset successfully! Redirecting to login...";
			title: "Reset Password";
			token_required: "Reset token is required";
		};
	};
	common: {
		actions: {
			actions: "Actions";
			open_menu: "Open menu";
			refresh_schemas: "Refresh Schemas";
			select_all: "Select all";
			select_row: "Select row";
			view_content: "View Content";
		};
		app_name: "QR Menu";
		buttons: {
			back: "Back";
			back_to_dashboard: "Back to dashboard";
			cancel: "Cancel";
			close: "Close";
			create: "Create";
			delete: "Delete";
			deleting: "Deleting...";
			edit: "Edit";
			go_back: "Go Back";
			leave: "Leave";
			loading: "Loading...";
			logging_in: "Logging in...";
			login: "Login";
			next: "Next";
			previous: "Previous";
			register: "Register";
			reset: "Reset";
			save: "Save";
			save_changes: "Save Changes";
			saving: "Saving...";
			stay: "Stay";
			submit: "Submit";
			view: "View";
		};
		confirmations: {
			are_you_sure: "Are you sure?";
			cannot_be_undone: "This action cannot be undone.";
			delete_item: "This will permanently delete this item.";
			delete_items: "This will permanently delete {{count}} selected items.";
			delete_menu: "This will permanently delete the menu and all its content.";
			unsaved_changes: "Unsaved Changes";
			unsaved_changes_description: "You have unsaved changes. Are you sure you want to leave? Your changes will be lost.";
		};
		empty_states: {
			empty: "Empty";
			no_content_found: "No content found";
			no_results: "No results.";
			not_found: "Not Found";
			unknown: "Unknown";
		};
		images: {
			alt: {
				auth_layout: "Authentication layout image";
			};
		};
		labels: {
			is_free: "Free";
			menu_name: "Menu Name";
			select_theme: "Select a theme";
			theme_selected: "Theme Selected: {{id}}";
		};
		messages: {
			content_schema_description: "Content schema for this menu item";
			items: "{{count}} items";
			no_properties_defined: "No properties defined";
			or_continue_with: "Or continue with";
			properties: "{{count}} properties";
			properties_defined: "{{count}} properties defined";
		};
		time: {
			daysAgo: "{{count}} day ago";
			daysAgo_plural: "{{count}} days ago";
			hoursAgo: "{{count}} hour ago";
			hoursAgo_plural: "{{count}} hours ago";
			justNow: "Just now";
			minutesAgo: "{{count}} minute ago";
			minutesAgo_plural: "{{count}} minutes ago";
		};
	};
	content: {
		add_new_content: "Add New Content";
		content_updated: "Content updated successfully";
		create_new_content: "Create a new content";
		failed_to_delete: "Failed to delete item(s)";
		failed_to_load: "Failed to load content item";
		failed_to_update: "Failed to update content";
		item_deleted: "Item deleted successfully";
		items_deleted: "Successfully deleted {{count}} items";
		loading_content: "Loading content...";
		new_content_dialog: {
			add_new_content: "Add New Content";
			success: "Content created successfully";
			title: "New Content";
		};
		no_content_description: "This menu doesn't have any content available.";
	};
	error: {
		"404": "404";
		"404_description": "The requested page could not be found.";
		error: "Error";
		error_getting_menu: "Error getting menu";
		error_getting_menus: "Error getting menus";
		error_getting_themes: "Error getting themes";
		error_loading_user_data: "Error loading user data";
		error_updating_menu: "Error updating menu";
		errors: "Errors";
		failed_to_create_menu: "Failed to create menu";
		failed_to_delete_menu: "Failed to delete menu";
		failed_to_load_content_data: "Failed to load content data";
		failed_to_load_menu_data: "Failed to load menu data";
		login_failed: "Login failed";
		requested_content_not_found: "The requested content could not be found.";
		unexpected_error: "An unexpected error occurred.";
		upload_failed: "Upload failed";
	};
	home: {
		all_menus_synchronized: "All your menus are synchronized with the latest build.";
		all_menus_up_to_date: "All Menus Up to Date";
		logged_in_success: "You are successfully logged in!";
		manage_menus: "Manage Menus";
		manage_themes: "Manage Themes";
		menu_preview_title: "Published Menus";
		menus_needing_rebuild: "Menus Needing Rebuild";
		menus_needing_rebuild_count: "{{count}} menu(s) need to be rebuilt";
		no_published_menus: "No published menus yet";
		no_recent_activity: "No recent activity";
		published: "Published";
		published_menus: "Published Menus";
		published_status: "Published";
		quick_actions_title: "Quick Actions";
		recent_activity_title: "Recent Activity";
		settings: "Settings";
		stats_widget_title: "Statistics";
		title: "Dashboard Home";
		total_menus: "Total Menus";
		unpublished: "Unpublished";
		unpublished_menus: "Unpublished Menus";
		unpublished_status: "Unpublished";
		view_all_menus: "View All Menus";
	};
	menu: {
		build: "Build";
		build_error: "Failed to build menu";
		build_publish: "Build & Publish";
		build_status_done: "Build completed successfully";
		build_status_failed: "Build failed";
		build_status_pending: "Preparing build...";
		build_status_processing: "Building menu...";
		build_success: "Menu built and published successfully";
		building: "Building...";
		change_theme: "Change Theme";
		check_availability: "Check Availability";
		checking_availability: "Checking...";
		content_title: "{{contentName}} Content";
		create_first_menu: "Create your first menu";
		delete_selected: "Delete Selected ({{count}})";
		domain_available: "Domain is available";
		domain_name: "Domain Name";
		domain_name_placeholder: "example.com";
		domain_taken: "Domain is taken, try another";
		edit_content: "Edit Content";
		edit_content_description: "Update the content for {{contentName}} in {{menuName}}";
		edit_content_title: "Edit {{contentName}} Content";
		error_checking_availability: "Error checking domain availability";
		generate_domain: "Generate Domain";
		menu_content: "Menu Content";
		menu_deleted_success: "Successfully deleted menu";
		menu_not_latest: "This menu has been modified since the last build. Please rebuild to publish the latest changes.";
		menu_up_to_date: "Menu is up-to-date";
		menu_updated_success: "Menu updated successfully";
		needs_rebuild: "Needs Rebuild";
		new_menu: "+ New Menu";
		no_menus: "No menus found.";
		no_schemas: "No schemas found";
		no_schemas_description: "This menu doesn't have any content schemas available.";
		open_in_new_tab: "Open in new tab";
		rebuild_menu: "Rebuild Menu";
		resuming_build: "Resuming build...";
		title: "Your Menus";
		unpublish: "Unpublish";
		unpublish_error: "Failed to unpublish menu";
		unpublish_success: "Menu unpublished successfully";
		view_published_site: "View Published Site";
	};
	settings: {
		account_details: {
			title: "Account Details";
		};
		appearance: {
			dark: "Dark";
			description: "Select the appearance for your account";
			light: "Light";
			system: "System";
			title: "Appearance";
		};
		billing_and_subscription: {
			title: "Billing & Subscription";
		};
		change_password: {
			error: "Failed to change password";
			submit: "Change Password";
			success: "Password changed successfully";
		};
		confirm_password: "Confirm Password";
		confirm_password_placeholder: "Confirm your new password";
		current_password: "Current Password";
		current_password_placeholder: "Enter your current password";
		language: {
			description: "Select the language for your account";
			select_language: "Select a language";
			title: "Language";
		};
		new_password: "New Password";
		new_password_placeholder: "Enter your new password";
		notifications: {
			title: "Notifications";
		};
		organization: {
			title: "Organization";
		};
		privacy: {
			title: "Privacy";
		};
		security: {
			title: "Security";
		};
		sessions: {
			current: "Current";
			current_session: "Current Session";
			description: "Manage your active sessions and sign out from other devices";
			device: "Device";
			last_active: "Last Active";
			location: "Location";
			no_sessions: "No active sessions found";
			terminate: "Terminate";
			terminate_all_others: "Terminate All Other Sessions";
			terminate_all_others_confirm: "Are you sure you want to terminate all other sessions? This will log you out from all other devices.";
			terminate_confirm: "Are you sure you want to terminate this session?";
			terminate_error: "Failed to terminate session";
			terminate_other: "Terminate Session";
			terminate_success: "Session terminated successfully";
			title: "Sessions";
		};
	};
	sidebar: {
		dashboard: "Dashboard";
		logout: "Logout";
		menu: "Menu";
		settings: "Settings";
		themes: "Themes";
	};
	theme: {
		all_themes: "All Themes";
		new_theme: "+ New Theme";
		no_themes: "No themes found.";
		register: {
			preview_image: "Theme Preview Image (optional)";
			success: "Theme registered successfully";
			theme_zip_file: "Theme ZIP File";
			title: "Theme Register";
		};
		select_theme_description: "Select a theme from the list below";
		title: "Themes";
	};
	ui_components: {
		dialog: {
			close: "Close";
		};
		form: {
			modified: "(modified)";
		};
		pagination: {
			more_pages: "More pages";
			more_pages_aria_label: "More pages";
			next: "Next";
			next_aria_label: "Go to next page";
			pagination: "Page navigation";
			previous: "Previous";
			previous_aria_label: "Go to previous page";
		};
		sheet: {
			close: "Close";
		};
		sidebar: {
			sidebar: "Sidebar";
			sidebar_description_mobile: "Displays the mobile sidebar.";
			toggle_sidebar: "Toggle Sidebar";
		};
	};
	validation: {
		confirm_password_min: "Confirm Password must be at least 8 characters";
		file_upload_image: "Please upload an image file, and less than 5MB";
		file_upload_zip: "Please upload a zip file, and less than 5MB";
		invalid_email: "Invalid email address";
		name_required: "Name is required";
		password_min: "Password must be at least 8 characters";
		passwords_dont_match: "Passwords don't match";
		theme_required: "Theme is required";
		username_min: "Username must be at least 3 characters";
		username_or_email_invalid: "Must be a valid username or email";
		username_or_email_min: "Username or email must be at least 3 characters";
	};
}

export default Resources;
